secrets:
  secrets_env:
    file: .env

services:
  bug-tracker-db:
    image: postgres:16-alpine
    container_name: bug-tracker-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - bug-track-db-v:/var/lib/postgresql/data
    secrets:
      - secrets_env

volumes:
  bug-track-db-v:
    name: bug-track-db-v
    driver: local
    driver_opts:
      o: bind
      type: none
      device: './database/'